
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: r1
          uri: http://localhost:8088/
          predicates:
            - Path=/clients/**
        - id: r2
          uri: http://localhost:8088/
          predicates:
            - Path=/client/**
